{"name": "test_candidate_invitation", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://prod-job-service.ambitionhire.ai/get-batches?manual=true&page=1&limit=10", "trace": "client = <api_client.APIClient object at 0x00000225B9B8F920>\n\n    def test_candidate_invitation(client):\n>       candidate_invitation_data = client.get_candidate_invitation(page=1,limit=10)\n\ntest_login.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\api_client.py:196: in get_candidate_invitation\n    response.raise_for_status()  # Raise an exception if the request failed\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [404]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://prod-job-service.ambitionhire.ai/get-batches?manual=true&page=1&limit=10\n\nC:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:1021: HTTPError"}, "start": 1737115686571, "stop": 1737115687503, "uuid": "914d270e-67ae-4a38-978b-8dc97adf0c2a", "historyId": "554ebec1d548be9ed95730768a407838", "testCaseId": "554ebec1d548be9ed95730768a407838", "fullName": "tests.API.test_login#test_candidate_invitation", "labels": [{"name": "parentSuite", "value": "tests.API"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-HRHMBRL"}, {"name": "thread", "value": "11592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.API.test_login"}]}