{"name": "test_role_based_access", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://prod-job-service.ambitionhire.ai/v1/roles/custom-roles/?client_name=Services", "trace": "client = <api_client.APIClient object at 0x000001A3686C8080>\n\n    def test_role_based_access(client):\n>       role_based_access_data = client.get_role_based_access()\n\ntest_login.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\api_client.py:251: in get_role_based_access\n    response.raise_for_status()  # Raise an exception if the request failed\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [404]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://prod-job-service.ambitionhire.ai/v1/roles/custom-roles/?client_name=Services\n\nC:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:1021: HTTPError"}, "start": 1737117666382, "stop": 1737117676097, "uuid": "a8dd451f-7dcc-4a02-a378-cea9a9bfcfc2", "historyId": "0129f58a30b5f7190eb2b5eaf9f0c85b", "testCaseId": "0129f58a30b5f7190eb2b5eaf9f0c85b", "fullName": "tests.API.test_login#test_role_based_access", "labels": [{"name": "parentSuite", "value": "tests.API"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-HRHMBRL"}, {"name": "thread", "value": "7676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.API.test_login"}]}