{"name": "test_login", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://prod-auth-service.ambitionhire.ai/v1/auth_routes/recruiter-login/", "trace": "@pytest.fixture(scope=\"module\")\n    def client():\n        api_client = APIClient()\n>       api_client.login(\n            email=CREDENTIALS[\"email\"],\n            password=CREDENTIALS[\"password\"],\n            client_name=CREDENTIALS[\"client_name\"],\n        )\n\ntest_login.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\api_client.py:49: in login\n    response.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [405]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://prod-auth-service.ambitionhire.ai/v1/auth_routes/recruiter-login/\n\nC:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:1021: HTTPError"}, "start": 1738322462325, "stop": 1738322462325, "uuid": "b3f3ccf2-a836-45a3-8f73-a6292e088c2f", "historyId": "edf0f70bc2e89eec38a945fd0769f980", "testCaseId": "edf0f70bc2e89eec38a945fd0769f980", "fullName": "tests.API.test_login#test_login", "labels": [{"name": "tag", "value": "APItest"}, {"name": "parentSuite", "value": "tests.API"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-HRHMBRL"}, {"name": "thread", "value": "22020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.API.test_login"}]}