{"uuid": "e12daefd-f496-4f44-a38d-5db27cc407b7", "children": ["6cfc3c38-1124-4e60-a94b-5f0d610d475c", "6f4ea9d9-442e-494a-bdf7-bc38d91f62e5", "f0d4486c-5103-4e31-9ea1-02797bb12175", "f8007d43-fb85-480c-b35e-1a37e4850219", "635059f0-e6c3-4a7a-8a38-c1e7f58d957a", "1eb20ad5-fc98-4d81-b378-b05741c8d854"], "befores": [{"name": "authenticated_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'url' must be a string\n  (Session info: chrome=131.0.6778.205)\nStacktrace:\n\tGetHandleVerifier [0x0083EC13+23731]\n\t(No symbol) [0x007CC394]\n\t(No symbol) [0x006ABE63]\n\t(No symbol) [0x0072BF46]\n\t(No symbol) [0x00711E5C]\n\t(No symbol) [0x0072B46E]\n\t(No symbol) [0x00711BF6]\n\t(No symbol) [0x006E3F35]\n\t(No symbol) [0x006E4EBD]\n\tGetHandleVerifier [0x00B1F0D3+3039603]\n\tGetHandleVerifier [0x00B32DEA+3120778]\n\tGetHandleVerifier [0x00B2B592+3089970]\n\tGetHandleVerifier [0x008D43B0+635984]\n\t(No symbol) [0x007D4DCD]\n\t(No symbol) [0x007D2068]\n\t(No symbol) [0x007D2205]\n\t(No symbol) [0x007C4FD0]\n\tBaseThreadInitThunk [0x7710FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C2809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C2806E+238]\n\n", "trace": "  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\Desktop\\Ambition hire file\\Ambition hire\\conftest.py\", line 142, in authenticated_user\n    login.get(env)\n  File \"C:\\Users\\Dell\\Desktop\\Ambition hire file\\Ambition hire\\Pages_Candidate\\base_page.py\", line 20, in get\n    self.driver.get(url)\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735888330874, "stop": 1735888330880}], "start": 1735888330874, "stop": 1735888331175}